service: serverlessTodos
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  region: eu-west-2

plugins:
  - serverless-plugin-typescript

functions:
  addTodo:
    handler: src/handler/addTodo.handler
    events:
      - httpApi:
          path: /add-todo
          method: post
  getTodos:
    handler: src/handler/getTodos.handler
    events:
      - httpApi:
          path: /
          method: get

resources:
  Resources:
    todosTable:
      Type: "AWS::DynamoDB::Table"
      Properties:
        TableName: todosTable
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH

