service: serverlessTodos
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  region: eu-west-2

plugins:
  - serverless-plugin-typescript

functions:
  addTodo:
    handler: src/handler/addTodo.handler
    events:
      - httpApi:
          path: /add-todo
          method: get
  getTodos:
    handler: src/handler/getTodos.handler
    events:
      - httpApi:
          path: /
          method: get
